### PR TITLE
Cleaning a few proof scripts

### PR DESCRIPTION
**Pull request by vbgl**
Overlay for https://github.com/coq/coq/pull/11018

### CODE REVIEW

**Comment by vbgl** [comment]
This is also an overlay for https://github.com/coq/coq/pull/11760

**Comment by Zimmi48** [comment]
@fblanqui In principle, this patch should be backward compatible. Would you mind merging it soon?

**Comment by fblanqui** [comment]
Hi @Zimmi48 . I do not see any result from Travis. Do you know how to get Travis run on your PR?

**Comment by fblanqui** [comment]
Sorry, I found it, but Github doesn't show the result. Do you know what to do on Github to make it show the results of Travis?

**Comment by Zimmi48** [comment]
@fblanqui It seems like a bug of Travis that the status was not reported to GitHub. Many previous PRs did get their CI status reported. Note though that Travis is planning to move away all open source projects from travis-ci.org to travis-ci.com (and the two websites do not report their statuses in the same way). You can request to migrate your repository to travis-ci.com (https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg) and it is likely that it will fix this issue.

**Pull request merged**
