### PR TITLE
Adapt w.r.t coq/coq#16004

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by fblanqui** [comment]
Hello @Alizter . This change does not seem backward compatible with Coq <= 8.13. Is this right?

**Comment by Alizter** [comment]
Hi @fblanqui this is correct.

**Comment by fblanqui** [comment]
What's your plan? Are you going to try to find a backward compatible solution?

**Comment by Alizter** [comment]
@fblanqui Unfortunately this one was prepared incorrectly causing some local instances to become global. Another PR will be submitted with a proper patch.

I have no plans to find a backwards compatible solution, but others have discussed this want on Zulip: https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/.5Bdisc.5D.20Make.20hint.20locality.20warning.20an.20error.

**Pull request closed without merging**
