### PR TITLE
Adapt to Coq/Coq#18164

### PR DESCRIPTION
**Pull request by Villetaneuse**
This adapts to the removal of many Coq.Arith files.

### CODE REVIEW

**Comment by Villetaneuse** [comment]
@fblanqui sorry to bother you, this is for Coq/Coq#18164

**Comment by fblanqui** [comment]
Hello. All CI failed...

**Comment by Villetaneuse** [comment]
> Hello. All CI failed...

Sorry! I will investigate this this afternoon. This should have passed at least on dev...

**Comment by Villetaneuse** [comment]
I can't reproduce the failure on my side, even after rebasing. It should at least pass on Coq's master branch. Still I have simplified one proof. Maybe dev, 8.18 and 8.17 will pass this time. For the other ones, especially 8.14 and 8.15 I will need to add some missing PeanoNat lemmas in Util/Nat/NatUtil.v (and change again some other files). Do you confirm you target Coq 8.14 as the minimal supported version for your master branch?

I'm sorry that it does not pass easily the tests, but this library is quite huge and I had to change 96 files to make it compile on my machine.

**Comment by fblanqui** [comment]
Hi. There are still errors that I can reproduce on my machine with coq 8.18:
```
File "./Util/Polynom/Polynom.v", line 62, characters 33-39:
Warning: Notation lt_S_n is deprecated since 8.16.
The Arith.Lt file is obsolete. Use the bidirectional version Nat.succ_lt_mono instead.
[deprecated-syntactic-definition-since-8.16,deprecated-since-8.16,deprecated-syntactic-definition,deprecated,default]
File "./Util/Polynom/Polynom.v", line 62, characters 40-41:
Error:
In environment
mxi : forall n i : nat, (i < n)%nat -> monom n
n : nat
n' : nat
i : nat
n0 : nat
h : (S n0 < S n')%nat
The term "h" has type "(S n0 < S n')%nat" while it is expected to have type
 "nat".
```

**Comment by Villetaneuse** [comment]
Sorry again. This is very strange. On my local build `Arith.Lt` does not even exist any more, so this should have failed too.

**Comment by fblanqui** [comment]
make sure you start from a fresh and clean checkout: do make clean-all

**Comment by Villetaneuse** [comment]
I get it... some lemmas now added to Util/Nat/NatUtil are shadowed by some lemmas in Arith which are still present outside my Coq PR. Hence the different implicit arguments and the failures. I will do something cleaner with a MyNat module inside Util/Nat/NatUtil. I will also try to make it compatible with 8.14.

Sorry for the mistake.

**Comment by fblanqui** [comment]
and eval opam env to have the right coq version

**Comment by fblanqui** [comment]
Just permute Require's in Util/Polynom/Polynom.v.

**Comment by Villetaneuse** [comment]
> Just permute Require's.

Ok, I'll do this and add some missing stuff in NatUtil to compile it against 8.14 8.15 and 8.16

**Comment by fblanqui** [comment]
In NatUtil.v, some arguments should be declared as implicits:
```
Lemma le_lt_n_Sm : forall {n m : nat}, n <= m -> n < S m.
```

**Comment by fblanqui** [comment]
There is a problem in APolyInt.v. I don't know how to solve it.

**Comment by Villetaneuse** [comment]
> There is a problem in APolyInt.v. I don't know how to solve it.

What is this problem?

**Comment by Villetaneuse** [comment]
@fblanqui sorry to bother you again. This should be ok now (tested locally against 8.14, 8.16 and dev). This was quite the nightmare though: some parts of the library assume implicit arguments, others do not. Importing Util/Nat/NatUtil.v populates the environment with many implicit arguments so it was not possible to add the missing compatibility lemmas there without breaking too many things. So in the end, I put them in a new Util/Nat/NatCompat.v file and always (partially) qualified these lemmas to avoid incompatibility with existing lemmas in Coq <8.19.

**Comment by fblanqui** [comment]
Thanks!

**Pull request merged**
