### PR TITLE
Adapt w.r.t. coq/coq#16004.

### PR DESCRIPTION
**Pull request by ppedrot**
Should be backwards compatible.

### CODE REVIEW

**Comment by Alizter** [comment]
*backwards compatible up to 8.14.

@fblanqui Unfortunately, apart from completely ignoring the warning (and thus silently switching from #[global] to #[export]) there is no way to keep comparability with <= 8.13.

**Comment by fblanqui** [comment]
Hello. I would appreciate very much if you could update the file coq-color.opam as well.

**Comment by ppedrot** [comment]
@fblanqui done.

**Comment by ppedrot** [comment]
@fblanqui ping

**Comment by fblanqui** [comment]
The CI fails with coq-dev. Do you know why?

**Comment by fblanqui** [comment]
I checked: it compiles with coq/master. What is wrong in https://github.com/fblanqui/color/blob/master/.github/workflows/docker-action.yml?

**Comment by ppedrot** [comment]
No idea. I'd suggest asking on Zulip.

**Comment by Alizter** [comment]
cc @erikmd

**Comment by erikmd** [comment]
Hi, thanks for the ping.

The non-availability of coqorg/coq:dev is a known issue (cf. e.g. [this stream](https://coq.zulipchat.com/#narrow/stream/237663-coq-community-devs-.26-users/topic/coq.3Adev.20Docker.20tag.20currently.20unavailable/near/282503558) on Zulip)

Fixing this is definitely on my backlog, but I won't be able to look after this before Wednesday evening.

In the meantime, you can just replace this line:

https://github.com/fblanqui/color/blob/70f8d37fdaf8c4c973419e0475ccb32020530a30/.github/workflows/docker-action.yml#L21

with:

```yaml
- 'coqorg/coq:dev-ocaml-4.13-flambda'
```

**Pull request merged**
